language: ruby
rvm:
  - "2.3.1"
env:
  - DB=mysql
script:
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rspec
before_script:
  - bundle install
  - mysql -e 'create database myapp_test'
services:
  - mysql
